[theme]
primaryColor = "#5EA3FD"
backgroundColor = "#f0f2f6"
secondaryBackgroundColor = "#e0e5ec"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false